# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
    replaces-base: true

updates:
  - package-ecosystem: npm
    directory: "/codbex-hermes"
    registries:
      - npm-github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
