apiVersion: apps/v1
kind: Deployment
metadata:
  name: codbex-hermes
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codbex-hermes
  template:
    metadata:
      labels:
        app: codbex-hermes
    spec:
      containers:
        - name: codbex-hermes
          image: ghcr.io/codbex/codbex-hermes:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - containerPort: 80
