name: Build - Application

on:
  push:
    branches:
      - main

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-build.yaml@main
    with:
      packages-build: codbex-hermes
    secrets: inherit